import * as React from "react";

import { cn } from "@/lib/utils";

/**
 * Global shape exposed by the Genuin SDK script once it has loaded.
 * Declared as an ambient type so we can call `window.genuin.init(...)`
 * in strict mode without `any`.
 */
declare global {
  interface Window {
    genuin?: {
      init: (config: GenuinInitConfig) => void;
    };
  }
}

/**
 * Config object passed straight to `window.genuin.init(...)`. The SDK
 * accepts either the (`style_id` + `placement_id`) pair OR the shortcut
 * `embed_id`. `api_key` is always required.
 */
export interface GenuinInitConfig {
  style_id?: string;
  placement_id?: string;
  embed_id?: string;
  api_key: string;
  /** Optional initial video id list, rendered via `data-initial-video-ids`. */
  initial_video_ids?: string[];
}

export interface GenuinPlacementProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "id"> {
  /**
   * Genuin style id — identifies the visual style the placement renders in.
   * Required unless you pass `embedId`.
   */
  styleId?: string;
  /**
   * Genuin placement id — identifies *which* placement (content surface)
   * to fetch. Required unless you pass `embedId`.
   */
  placementId?: string;
  /** Shortcut id that bundles style + placement. Alternative to the pair above. */
  embedId?: string;
  /** Genuin API key. Always required. */
  apiKey: string;
  /**
   * List of video ids to preload into the placement. Renders as the
   * `data-initial-video-ids` attribute on the host div, which is what the
   * SDK reads at init time.
   */
  initialVideoIds?: string[];
  /**
   * URL of the Genuin SDK script to load. Defaults to `/dist/gen_sdk.js`
   * so it matches the reference HTML page. Pass a CDN URL for production.
   */
  scriptSrc?: string;
  /**
   * DOM id to use for the host div. Defaults to an autogenerated unique id
   * so multiple placements can coexist on one page.
   */
  id?: string;
  /** Width of the placement slot. Defaults to 600. */
  width?: number | string;
  /** Height of the placement slot. Defaults to 600. */
  height?: number | string;
}

/**
 * Tracks which SDK URLs are already in flight so that multiple
 * `GenuinPlacement` components on the same page do not each append a
 * duplicate `<script>` tag.
 */
const sdkLoaders = new Map<string, Promise<void>>();

function loadGenuinSdk(src: string): Promise<void> {
  if (typeof window === "undefined") {
    return Promise.resolve();
  }
  if (window.genuin?.init) {
    return Promise.resolve();
  }
  const existing = sdkLoaders.get(src);
  if (existing) {
    return existing;
  }
  const promise = new Promise<void>((resolve, reject) => {
    const already = document.querySelector<HTMLScriptElement>(
      `script[data-genuin-sdk="${src}"]`,
    );
    if (already) {
      already.addEventListener("load", () => resolve(), { once: true });
      already.addEventListener(
        "error",
        () => reject(new Error(`Failed to load ${src}`)),
        { once: true },
      );
      return;
    }
    const tag = document.createElement("script");
    tag.src = src;
    tag.async = true;
    tag.dataset.genuinSdk = src;
    tag.addEventListener("load", () => resolve(), { once: true });
    tag.addEventListener(
      "error",
      () => reject(new Error(`Failed to load ${src}`)),
      { once: true },
    );
    document.body.appendChild(tag);
  });
  sdkLoaders.set(src, promise);
  return promise;
}

let autoId = 0;
function useGeneratedId(prefix: string, override: string | undefined): string {
  const [id] = React.useState(() => {
    if (override) return override;
    autoId += 1;
    return `${prefix}-${autoId}`;
  });
  return id;
}

/**
 * Thin React wrapper around the Genuin SDK. Mount once, pass your ids, and
 * the component will:
 *
 *   1. Inject the SDK script tag the first time any placement mounts.
 *   2. Wait for `window.genuin` to be available.
 *   3. Call `window.genuin.init({...})` with the props you supplied.
 *
 * The placement renders into a unique div the component controls, so you
 * can have multiple `<GenuinPlacement />` instances on one page.
 *
 * Example:
 *   <GenuinPlacement
 *     styleId="699d6af290cd354baa3b046a"
 *     placementId="699d6af290cd354baa3b0469"
 *     apiKey="your-api-key"
 *     initialVideoIds={["id1", "id2"]}
 *   />
 */
export function GenuinPlacement({
  styleId,
  placementId,
  embedId,
  apiKey,
  initialVideoIds,
  scriptSrc = "/dist/gen_sdk.js",
  id,
  width = 600,
  height = 600,
  className,
  style,
  ...rest
}: GenuinPlacementProps) {
  const hostId = useGeneratedId("gen-sdk", id);
  const [status, setStatus] = React.useState<
    "idle" | "loading" | "ready" | "error"
  >("idle");
  const [errorMessage, setErrorMessage] = React.useState<string | null>(null);

  React.useEffect(() => {
    let cancelled = false;

    if (!apiKey) {
      setStatus("error");
      setErrorMessage("GenuinPlacement: `apiKey` is required.");
      return () => {
        cancelled = true;
      };
    }
    if (!embedId && (!styleId || !placementId)) {
      setStatus("error");
      setErrorMessage(
        "GenuinPlacement: pass either `embedId` or both `styleId` and `placementId`.",
      );
      return () => {
        cancelled = true;
      };
    }

    setStatus("loading");
    setErrorMessage(null);

    loadGenuinSdk(scriptSrc)
      .then(() => {
        if (cancelled) return;
        if (!window.genuin?.init) {
          throw new Error(
            "Genuin SDK loaded but window.genuin.init is not defined.",
          );
        }
        const config: GenuinInitConfig = { api_key: apiKey };
        if (embedId) {
          config.embed_id = embedId;
        } else {
          config.style_id = styleId;
          config.placement_id = placementId;
        }
        if (initialVideoIds && initialVideoIds.length > 0) {
          config.initial_video_ids = initialVideoIds;
        }
        window.genuin.init(config);
        if (!cancelled) {
          setStatus("ready");
        }
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setStatus("error");
        setErrorMessage(err instanceof Error ? err.message : String(err));
      });

    return () => {
      cancelled = true;
    };
  }, [apiKey, embedId, styleId, placementId, scriptSrc, initialVideoIds]);

  const mergedStyle: React.CSSProperties = {
    width,
    height,
    ...style,
  };

  return (
    <div
      data-slot="genuin-placement"
      data-status={status}
      className={cn("bg-muted/40 overflow-hidden rounded-md", className)}
      style={mergedStyle}
      {...rest}
    >
      <div
        id={hostId}
        className="gen-sdk-class h-full w-full"
        data-initial-video-ids={
          initialVideoIds && initialVideoIds.length > 0
            ? initialVideoIds.join(",")
            : undefined
        }
      />
      {status === "error" && errorMessage && (
        <div className="text-destructive p-3 text-xs" role="alert">
          {errorMessage}
        </div>
      )}
    </div>
  );
}
